[project]
version = "0.0.1"
name = "tracks"
dependencies = [
    "langchain",
    "langchain_google_vertexai",
    "langgraph",
    "pydantic",
    "pydantic-tfl-api",
    "dotenv",
    "python-telegram-bot"
]

[tool.isort]
profile = "black"
